# Generated by Django 3.1.7 on 2021-03-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210309_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='book',
            field=models.ManyToManyField(to='store.Book', verbose_name='book'),
        ),
    ]
