# Generated by Django 3.1.7 on 2021-04-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210331_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author']},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['book']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['book']},
        ),
        migrations.AlterModelOptions(
            name='publishinghouse',
            options={'ordering': ['name']},
        ),
    ]
