# Generated by Django 3.1.7 on 2021-03-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210311_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='sold'),
        ),
    ]
