# Generated by Django 3.1.7 on 2021-03-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_book_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sold',
        ),
        migrations.AddField(
            model_name='book',
            name='numb_of_books',
            field=models.PositiveIntegerField(default=0, verbose_name='Numer of books'),
        ),
    ]
