# Generated by Django 3.1.7 on 2021-03-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210316_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='numb_of_books',
            field=models.PositiveIntegerField(default=1, verbose_name='Numer of books'),
        ),
    ]
