# Generated by Django 3.1.7 on 2021-03-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210316_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='numb_of_books',
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
