# Generated by Django 3.1.7 on 2021-03-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wharehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='sold'),
        ),
    ]
