# Generated by Django 3.1.7 on 2021-03-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wharehouse', '0004_auto_20210326_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author']},
        ),
    ]
