# Generated by Django 3.1.7 on 2021-03-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wharehouse', '0007_auto_20210326_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
