# Generated by Django 3.1.7 on 2021-04-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wharehouse', '0008_auto_20210326_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book',
            field=models.CharField(max_length=100, verbose_name='book'),
        ),
    ]
